# Generated by Django 2.2.1 on 2019-05-27 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favourite',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='foodtype',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='foodtypes',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='rate',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='restype',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'managed': True},
        ),
    ]
