# Generated by Django 2.2.1 on 2019-05-30 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtype',
            name='food_type',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
