# Generated by Django 2.2.1 on 2019-06-01 14:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_auto_20190601_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='restid',
            field=models.ForeignKey(db_column='restid', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='mainsite.Restaurant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodtypes',
            name='food_type',
            field=models.ForeignKey(blank=True, db_column='food_type', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainsite.FoodType'),
        ),
        migrations.AddField(
            model_name='foodtypes',
            name='menuid',
            field=models.ForeignKey(blank=True, db_column='menuid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainsite.Menu'),
        ),
        migrations.AddField(
            model_name='menu',
            name='restid',
            field=models.ForeignKey(db_column='restid', default=django.utils.timezone.now, on_delete=django.db.models.deletion.DO_NOTHING, to='mainsite.Restaurant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rate',
            name='restid',
            field=models.ForeignKey(blank=True, db_column='restid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainsite.Restaurant'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='rtype_name',
            field=models.ForeignKey(blank=True, db_column='rtype_name', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainsite.ResType'),
        ),
        migrations.AlterField(
            model_name='foodtypes',
            name='typesid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menuid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rate',
            name='rateid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='update_date',
            field=models.DateField(auto_now=True),
        ),
    ]
