# Generated by Django 2.2.1 on 2019-06-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_auto_20190601_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodtypes',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='create_at',
        ),
        migrations.AlterField(
            model_name='foodtypes',
            name='typesid',
            field=models.FloatField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menuid',
            field=models.FloatField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rate',
            name='rateid',
            field=models.FloatField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restid',
            field=models.FloatField(primary_key=True, serialize=False),
        ),
    ]
