# Generated by Django 2.2.1 on 2019-06-03 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_auto_20190601_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='userid',
            field=models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.DO_NOTHING, to='mainsite.UserInfo'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='restid',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='rate',
            name='userid',
            field=models.ForeignKey(blank=True, db_column='userid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainsite.UserInfo'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='update_date',
            field=models.CharField(max_length=20),
        ),
    ]
